[package]
name = "vox_box"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]

[lib]
name = "vox_box"
doctest = false
crate-type = ["dylib", "rlib"]

[dependencies]
num = "*"
sample = "*"
libc = "*"
clippy = "*"

[profile.release]
lto = true
