[package]
name = "vox_box"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]

[lib]
name = "vox_box"
doctest = false
crate-type = ["dylib", "rlib"]

[dependencies]
num = "0.1"
rand = "0.3"
sample = "0.2"
libc = "0.2"
rustfft = "1.0"

[profile.release]
lto = true
