[package]
name = "vox_box"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]

[lib]
name = "vox_box"

[dependencies]
num = "*"
sample = "*"

[profile.release]
lto = true
