[package]
name = "vox_box"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]
description = "A tool to process speech audio in Rust"
documentation = "http://www.andrewchristophersmith.com/docs/vox_box/vox_box/index.html"
repository = "https://github.com/andrewcsmith/vox_box.rs"
readme = "README.md"
keywords = ["audio", "fft", "nlp"]
license = "MIT"

[lib]
name = "vox_box"
doctest = false
crate-type = ["dylib", "rlib"]

[dependencies]
num = "0.1"
rand = "0.3"
sample = "0.2"
libc = "0.2"
rustfft = "1.0"
rustc-serialize = "0.3"

[dev-dependencies]
docopt = "0.6"
nalgebra = "0.5.1"
hound = "1.0"
byteorder = "0.4"

[profile.release]
lto = true
