[package]
name = "vox_box"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]
include = ["src/**/*.rs", "Cargo.toml"]

[lib]
name = "vox_box"
doctest = false
crate-type = ["dylib", "rlib"]

[dependencies]
num = "0.1.27"
sample = "0.1.3"
libc = "0.2.2"
clippy = "0.0.23"

[profile.release]
lto = true
