[package]
name = "formant_extractor"
version = "0.1.0"
authors = ["Andrew Smith <andrewchristophersmith@gmail.com>"]

[dependencies]
num = "0.1"
hound = "2.0"
sample = "0.10"
vox_box = { path = "../.." }
rustfft = { git = "https://github.com/abdul-rehman0/RustFFT" }
clap = "*"
num-complex = "0.2"

